### PR TITLE
[IMPROVE] mainstage design with coutdown, local date showtime and speakers

### PR DESCRIPTION
**Pull request by sidmohanty11**
- Added a countdown similar to livestorm's
- Added locale time for showing the date (in my case 3;30PM Asia/Calcutta) (similar to livestorm)
- Added `topic` to the schema of speakers
- On the day of the event (when the timer expires, it will change to **We are now live!**) and "The date of the summit will be April 6th starting at ..." will change to **Event is live now!✨**
## MAINSTAGE

communityrcspeakers

## STRAPI

strapispeakers

### CODE REVIEW

**Comment by Sing-Li** [comment]
@sidmohanty11   please add somewhere visible in BOLD letters:

Bookmark this page and come back on April 6 for the LIVE conference

**Comment by Sing-Li** [comment]
@sidmohanty11 please update with the new format we talked about in the meeting.

**Comment by sidmohanty11** [comment]
Yes will update it asap, I just need some help with typography and placement of components for which @samad-yar-khan and @demonicirfan can help. Then we require the `headshots`  of speakers hosted on a CDN so that we can whitelist them in `next.config` file. Making the layout more appealing will be the goal, will keep you updated on the progress.

**Comment by Dnouv** [comment]
Hello @sidmohanty11 
I would love to contribute if you require any additional help with typography and placement of components. 
Please feel free to ping me. Thank you!

**Comment by sidmohanty11** [comment]
@Dnouv join here https://open.rocket.chat/group/2snhdmderhjmpjbpd?msg=ho2dYd2yJzwvqPkke

**Comment by Dnouv** [comment]
I tried but it states "Room does not exist or you may not have permission".

**Comment by sidmohanty11** [comment]
@Dnouv  I have added you in the discussion, please feel free to add your points to the design (check the thread for figma link)

**Comment by sidmohanty11** [comment]
@Sing-Li I've added content + bookmark alert and setup the barebone for speakers here, @samad-yar-khan will be adding to the backend schema of speakers (adding timing and "live" on the specific date functionalities). @demonicirfan can check with the typography and design. Please review this PR.
Thank you.

## Desktop
desktopview-speakers

## Mobile
mobileview-speakers

**Comment by samad-yar-khan** [comment]
> @Sing-Li I've added content + bookmark alert and setup the barebone for speakers here, @samad-yar-khan will be adding to the backend schema of speakers (adding timing and "live" on the specific date functionalities). @demonicirfan can check with the typography and design. Please review this PR. Thank you.
> 
> ## Desktop
> desktopview-speakers
> 
> ## Mobile
> mobileview-speakers

@sidmohanty11 Almost through with it. Will raise a PR by night and will start with the component for the main page after that

**Pull request merged**
