### PR TITLE
chore: declarative JS toolchain as code - via volta  --- reduces dev env variations (v1)

### PR DESCRIPTION
**Pull request by sidmohanty11**
- Pinned `v14.18.3` LTS using volta, for using this, users must have volta installed. This can be achieved using this command - `curl https://get.volta.sh | bash`
- audited and updated packages as required, now `/app/` has 0 vulnerability from 4 and `/cms/` has 14 vulnerabilities from 17
- Added `.nvmrc` file for managing node versions
- deleted redundant `/node_modules/` and `/package-lock.json` from root

## Preview

https://user-images.githubusercontent.com/73601258/169660879-09598924-c59a-4223-888f-110dc12e7cce.mp4

### CODE REVIEW

**Review by Sing-Li — COMMENTED** [review]
Please add to the main README.md the instruction / requirement to install volta

Thanks.

**Comment by sidmohanty11** [comment]
@Sing-Li please let me know if this is fine

**Review by Sing-Li — COMMENTED** [review]
Put this AFTER line 47.    Also avoid putting a SPECIFIC node version into README.md, as this will require changes everytime after strapi upgrade.   

In addition, we want to use this to enforce node / npm and other tool versions - for all distributred development team members --  and not just "node for strapi".   

Thanks.

**Review by Sing-Li — CHANGES_REQUESTED** [review]
see comments

**Comment by sidmohanty11** [comment]
@Sing-Li 
> Nodejs versioning is managed by [volta](https://docs.volta.sh/guide/). You can install it by running `curl https://get.volta.sh | bash` in your terminal. This is needed to ensure that Nodejs v14 and npm v6 are used for compatibility for all distributed development team members.

Can you please check, if this line is descriptive enough?

**Review by Sing-Li — CHANGES_REQUESTED** [review]
Please says "... only the appropriate version of nodeJS and npm to ensure ...."

**Comment by sidmohanty11** [comment]
@Sing-Li done :+1: , please check if I need to do some other changes.

Thank you!

**Review by Sing-Li — APPROVED** [review]
Thanks!  I'll merge this after all the automated tests.

Please start on the "stub" simple/trivial  auth component to ease the out-of-box dev experience.

**Comment by sidmohanty11** [comment]
@Sing-Li sure

**Pull request merged**
