### PR TITLE
[FIX] Remove Typos in JSX, Add Unique Keys to props and Add id field in Forms

### PR DESCRIPTION
**Pull request by samad-yar-khan**
-  [x] I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
  -  [x] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [ ] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  -  [ ] I have added necessary documentation (if applicable)
  - [x] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

 

- I added unique key props to cater to different environments. id for Strapii and _id for mongoDB.
- Fixed Typos in JSX.
- Added id in searchBox Toggle to avoid warning : [Issue](https://giters.com/chakra-ui/chakra-ui/issues/4328) image

- **Note**  : The only warning being displayed on console now are due to the issues persisting in the react-slick library. [Reference](https://github.com/akiran/react-slick/issues/1195)
 

## Issue(s)

Fixes : #58 

## Steps to test or reproduce

Mentioned in the Issue

## Before : 

https://user-images.githubusercontent.com/70485812/151192530-b3fb809c-35eb-4bdf-b778-d7e6277a8355.mp4

## After : 

https://user-images.githubusercontent.com/70485812/151193159-660f5aee-3e8b-46c4-8e4f-eaab48d1fd08.mp4

### CODE REVIEW

**Comment by Sing-Li** [comment]
What are the remaining 3 errors?   Are they unfixable?

**Comment by samad-yar-khan** [comment]
@Sing-Li Unfortunately, the issue is in the react-slick module. It has been closed but it still hasn't been solved [issue](https://giters.com/chakra-ui/chakra-ui/issues/4328).

**Comment by Sing-Li** [comment]
@RonLek   since it was your choice of component to use - do you think we should fork it and fix the problem?

**Comment by Sing-Li** [comment]
@samad-yar-khan   please resolve the conflicts.     We'll merge this after that.

**Comment by samad-yar-khan** [comment]
> @samad-yar-khan   please resolve the conflicts.     We'll merge this after that.

@Sing-Li , will surely do. I tried implement a hack to resolve the issue with the slick library, but didn't really work out. Apart from that I am not getting any other warnings from this branch. I will try to solve the issue one more time and update you on this thread.

**Comment by debdutdeb** [comment]
forcing workflow run

**Comment by samad-yar-khan** [comment]
@Sing-Li  Resolves Errors and Rebased with the current master branch. It would be great if you could take a look :smile:

**Comment by samad-yar-khan** [comment]
> @samad-yar-khan please resolve the conflicts. We'll merge this after that.

@Sing-Li  Resolved Errors and Rebased with the current master branch. It would be great if you could take a look :smile:

**Review by debdutdeb — APPROVED** [review]

**Pull request merged**
