### PR TITLE
fix: build error due to next/image

### PR DESCRIPTION
**Pull request by RonLek**
Fixes build error due to `next/image` by using [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images)

[Reference](https://stackoverflow.com/a/65509211/8316412)

### CODE REVIEW

**Comment by RonLek** [comment]
@debdutdeb @Sing-Li this should fix the error. Please take a look. Thanks.

**Comment by Sing-Li** [comment]
Thanks @RonLek    We had a short discussion and the best approach moving forward is to actually:

1.  remove `next export`
2.  add nodeJS server at the deployment site  behind nginx
3.  run the app in nextJS production mode at the deployment site

We'll start working on it tomorrow.

**Comment by debdutdeb** [comment]
I'll work on the deployment thing then

**Comment by Sing-Li** [comment]
Please do.  It is a brilliant idea.   And one that is very similar to @RonLek 's suggestion from the very first day last year when we started this prroject.

Except at that time, we had no ability to create docker images of github action.

**Comment by debdutdeb** [comment]
Closing since we're over this. Thanks @RonLek :)

**Pull request closed without merging**
