### PR TITLE
[NEW] simple automated testing

### PR DESCRIPTION
**Pull request by debdutdeb**
I'll probably add additional steps for deploying to a staging env later.

### CODE REVIEW

**Review by Sing-Li — CHANGES_REQUESTED** [review]
How will / can we hook in:

1) unit tests?
2) end to end tests?

Please add a few mock test placeholders in the right place so we can extend this.  Thanks.

**Comment by Sing-Li** [comment]
Adding a "push to production" on releases (not every commit/PR)  would be extremely helpful to close the CI/CD loop.   Please talk with @RonLek  on the production server community.rocket.chat deployment details.

**Comment by debdutdeb** [comment]
@Sing-Li - about push to production, already on it. I have the server details on hand :)

**Comment by debdutdeb** [comment]
About hooking tests in ci, depending on the testing framework and workflow, I'll add them once they're part of the project, no need to add placeholders atm :) Right now there are two simple tests to make sure the pr won't break deployment once merged.

**Comment by Sing-Li** [comment]
OK.   We're going to merge this.  With the caveat that if the resource consumption proves to be too much or too expensive (for the simple ack that - yes, it builds) then we will disable it.    Thanks  @debdutdeb !

**Pull request merged**
