### PR TITLE
[FIX] Fixed responsiveness of News Carousel

### PR DESCRIPTION
**Pull request by muneeb-i-khan**
So I have fixed the responsiveness of news carousel section. Also I have made styles consistent. 

First fix was making the styles consistent and you can check the results below:-

**Before**

fix1

**After**

fix1a

Second fix was making the section responsive. Earlier the text flowed outside the image. You can check the results below:- 
r4c

<a href="https://gitpod.io/#https://github.com/RocketChat/RC4Community/pull/208"></a>

### CODE REVIEW

**Comment by muneeb-i-khan** [comment]
[Palanikannan1437](https://github.com/Palanikannan1437) You can check it now.

**Comment by Palanikannan1437** [comment]
@muneeb-i-khan 

Awesome job on explaining the PR with all the screenshots and gifs 🙏!

Please refrain from changing the default styles of our component drastically(height, width, etc)...it was by design and well thought of by our contributors, please try to fix the responsiveness while keeping the current styles intact! Thank you! 😊

image

**Comment by muneeb-i-khan** [comment]
Okay I will try it👍

**Comment by muneeb-i-khan** [comment]
@Palanikannan1437 I restored all the default styles at places where it was possible. Tell me if there are any other changes required.

**Comment by muneeb-i-khan** [comment]
This fixes the following issue:- https://github.com/RocketChat/RC4Community/issues/205

**Comment by Palanikannan1437** [comment]
> Is it fine now or I need to make more changes? @Palanikannan1437 

Hey, it still doesn't keep the original changes... this was closed [in this](https://github.com/RocketChat/RC4Community/commit/549d4a7b46cd8d6f7cf67ca5a4a5b266c9b423d4)

Please consider closing this issue @muneeb-i-khan ....

Would love to see your contributions on the other open issues!! Thank you 🚀🚀

**Pull request closed without merging**
