### PR TITLE
add keycloak - initial

### PR DESCRIPTION
**Pull request by abhinavkrin**
This PR will add keycloak to RC4Community.

### CODE REVIEW

**Comment by Sing-Li** [comment]
This is awesome.    @debdutdeb can you please update our keycloak server and let's get community.rocket.chat working with REAL AUTH.       (just can't wait to see the linkage with superprofile  - hint Ronlek ;-)  )

**Comment by Sing-Li** [comment]
@abhinavkrin   please advise if this is good enough to merge for our upcoming Alumni Summit purpose

**Comment by Sing-Li** [comment]
Please also make keycloak the default IDM provider (if possible) for RC4Community instead of Firebase.

I've checked out the ISC license.   Totally OK to include.   Thanks.

**Comment by abhinavkrin** [comment]
> Please also make keycloak the default IDM provider (if possible) for RC4Community instead of Firebase.
> 
> I've checked out the ISC license. Totally OK to include. Thanks.

It's fine to merge this PR. The default IDM would be keycloak.
Currently.
The user will have the following attribute:
1. id
2. our custom access token
3.  image
4.  name
5.  email

**Comment by Sing-Li** [comment]
Please remove package-lock.json from the PR  (and perhaps add it to your .gitignore)  - thanks.

**Comment by abhinavkrin** [comment]
> Please remove `package-lock.json` from the PR (and perhaps add it to your .gitignore) - thanks. @abhinavkrin

Removed package-lock.json @Sing-Li

**Pull request merged**
